import type { Course } from "./types";
import { SKILL as S } from "./skills";

export const MOCK_COURSES: Course[] = [
  {
    id: "course-01",
    title: "React — The Complete Guide",
    provider: "Udemy",
    duration: "48 horas",
    skills: [S.REACT, S.FRONTEND, S.JAVASCRIPT],
    url: "https://www.udemy.com/course/react-the-complete-guide/",
  },
  {
    id: "course-02",
    title: "TypeScript Deep Dive",
    provider: "Frontend Masters",
    duration: "8 horas",
    skills: [S.TYPESCRIPT, S.JAVASCRIPT],
    url: "https://frontendmasters.com/courses/typescript-v4/",
  },
  {
    id: "course-03",
    title: "Next.js Foundations",
    provider: "Vercel",
    duration: "6 horas",
    skills: [S.NEXTJS, S.REACT, S.FRONTEND, S.JAVASCRIPT],
    url: "https://nextjs.org/learn",
  },
  {
    id: "course-04",
    title: "Vue 3 Masterclass",
    provider: "Vue School",
    duration: "30 horas",
    skills: [S.VUE, S.FRONTEND, S.JAVASCRIPT],
    url: "https://vueschool.io/courses",
  },
  {
    id: "course-05",
    title: "Angular — The Complete Guide",
    provider: "Udemy",
    duration: "36 horas",
    skills: [S.ANGULAR, S.FRONTEND, S.TYPESCRIPT],
    url: "https://www.udemy.com/course/the-complete-guide-to-angular-2/",
  },
  {
    id: "course-06",
    title: "Svelte for Beginners",
    provider: "freeCodeCamp",
    duration: "4 horas",
    skills: [S.SVELTE, S.FRONTEND, S.JAVASCRIPT],
    url: "https://www.freecodecamp.org/",
  },
  {
    id: "course-07",
    title: "CSS for JS Developers",
    provider: "Josh Comeau",
    duration: "20 horas",
    skills: [S.CSS, S.FRONTEND, S.UIUX],
    url: "https://css-for-js.dev/",
  },
  {
    id: "course-08",
    title: "Node.js — From Zero to Expert",
    provider: "Udemy",
    duration: "40 horas",
    skills: [S.NODE, S.BACKEND, S.JAVASCRIPT, S.API],
    url: "https://www.udemy.com/course/nodejs-the-complete-guide/",
  },
  {
    id: "course-09",
    title: "Python for Everybody",
    provider: "Coursera",
    duration: "64 horas",
    skills: [S.PYTHON, S.DATABASE, S.SQL],
    url: "https://www.coursera.org/specializations/python",
  },
  {
    id: "course-10",
    title: "Django for Professionals",
    provider: "Platzi",
    duration: "25 horas",
    skills: [S.BACKEND, S.PYTHON, S.API, S.REST, S.DATABASE],
    url: "https://platzi.com/cursos/django/",
  },
  {
    id: "course-11",
    title: "FastAPI — Modern Python Web",
    provider: "freeCodeCamp",
    duration: "8 horas",
    skills: [S.BACKEND, S.PYTHON, S.API, S.REST],
    url: "https://www.freecodecamp.org/",
  },
  {
    id: "course-12",
    title: "Spring Boot 3 & Spring Framework 6",
    provider: "Udemy",
    duration: "32 horas",
    skills: [S.BACKEND, S.JAVA, S.API, S.REST, S.SQL],
    url: "https://www.udemy.com/course/spring-boot-and-spring-framework-tutorial/",
  },
  {
    id: "course-13",
    title: "Go Programming — Mastering the Language",
    provider: "Coursera",
    duration: "30 horas",
    skills: [S.GO, S.BACKEND, S.API],
    url: "https://www.coursera.org/specializations/google-golang",
  },
  {
    id: "course-14",
    title: "SQL for Data Analysis",
    provider: "DataCamp",
    duration: "10 horas",
    skills: [S.SQL, S.DATABASE],
    url: "https://www.datacamp.com/courses/introduction-to-sql",
  },
  {
    id: "course-15",
    title: "MongoDB University",
    provider: "MongoDB",
    duration: "15 horas",
    skills: [S.NOSQL, S.DATABASE],
    url: "https://learn.mongodb.com/",
  },
  {
    id: "course-16",
    title: "Docker & Kubernetes Complete Guide",
    provider: "KodeKloud",
    duration: "32 horas",
    skills: [S.DOCKER, S.KUBERNETES, S.DEVOPS, S.CLOUD],
    url: "https://kodekloud.com/",
  },
  {
    id: "course-17",
    title: "AWS Cloud Practitioner Essentials",
    provider: "AWS Skill Builder",
    duration: "6 horas",
    skills: [S.CLOUD, S.DEVOPS],
    url: "https://aws.amazon.com/training/",
  },
  {
    id: "course-18",
    title: "CI/CD with GitHub Actions",
    provider: "freeCodeCamp",
    duration: "3 horas",
    skills: [S.CICD, S.DEVOPS, S.GIT],
    url: "https://www.freecodecamp.org/",
  },
  {
    id: "course-19",
    title: "Linux Command Line Basics",
    provider: "Udacity",
    duration: "3 horas",
    skills: [S.LINUX, S.DEVOPS],
    url: "https://www.udacity.com/course/linux-command-line-basics--ud595",
  },
  {
    id: "course-20",
    title: "Testing JavaScript Applications",
    provider: "Frontend Masters",
    duration: "10 horas",
    skills: [S.TESTING, S.JAVASCRIPT, S.NODE],
    url: "https://frontendmasters.com/courses/testing-javascript/",
  },
  {
    id: "course-21",
    title: "React Native — The Practical Guide",
    provider: "Udemy",
    duration: "38 horas",
    skills: [S.MOBILE, S.REACT, S.JAVASCRIPT, S.FRONTEND],
    url: "https://www.udemy.com/course/react-native-the-practical-guide/",
  },
  {
    id: "course-22",
    title: "Flutter & Dart — Complete Guide",
    provider: "Udemy",
    duration: "42 horas",
    skills: [S.MOBILE, S.DART, S.FRONTEND],
    url: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/",
  },
  {
    id: "course-23",
    title: "DevOps Foundations",
    provider: "Platzi",
    duration: "20 horas",
    skills: [S.DEVOPS, S.DOCKER, S.CICD, S.LINUX, S.CLOUD],
    url: "https://platzi.com/cursos/devops/",
  },
  {
    id: "course-24",
    title: "Machine Learning — Stanford",
    provider: "Coursera",
    duration: "60 horas",
    skills: [S.AI, S.DATA_SCIENCE, S.PYTHON],
    url: "https://www.coursera.org/learn/machine-learning",
  },
  {
    id: "course-25",
    title: "Blockchain A-Z — Build a Blockchain",
    provider: "Udemy",
    duration: "20 horas",
    skills: [S.BLOCKCHAIN, S.PYTHON, S.SECURITY],
    url: "https://www.udemy.com/course/build-your-blockchain-az/",
  },
  {
    id: "course-26",
    title: "Complete C# Unity Game Developer",
    provider: "Udemy",
    duration: "50 horas",
    skills: [S.GAME_DEV, S.CSHARP, S.MOBILE],
    url: "https://www.udemy.com/course/unitycourse2/",
  },
  {
    id: "course-27",
    title: "API Design & REST Fundamentals",
    provider: "freeCodeCamp",
    duration: "4 horas",
    skills: [S.API, S.REST, S.BACKEND],
    url: "https://www.freecodecamp.org/",
  },
  {
    id: "course-28",
    title: "GraphQL with Apollo",
    provider: "Apollo Graph Academy",
    duration: "12 horas",
    skills: [S.GRAPHQL, S.API, S.FRONTEND, S.BACKEND],
    url: "https://www.apollographql.com/tutorials/",
  },
  {
    id: "course-29",
    title: "Application Security Fundamentals",
    provider: "OWASP",
    duration: "8 horas",
    skills: [S.SECURITY, S.BACKEND, S.API],
    url: "https://owasp.org/",
  },
  {
    id: "course-30",
    title: "Kotlin for Android Developers",
    provider: "Google",
    duration: "20 horas",
    skills: [S.MOBILE, S.KOTLIN],
    url: "https://developer.android.com/courses",
  },
  {
    id: "course-31",
    title: "C++ Fundamentals",
    provider: "freeCodeCamp",
    duration: "12 horas",
    skills: [S.CPP],
    url: "https://www.freecodecamp.org/",
  },
  {
    id: "course-32",
    title: "Full Stack Web Development",
    provider: "Coursera",
    duration: "40 horas",
    skills: [S.FULLSTACK, S.FRONTEND, S.BACKEND, S.NODE],
    url: "https://www.coursera.org/",
  },
  {
    id: "course-33",
    title: "PHP & Laravel — From Scratch",
    provider: "Laracasts",
    duration: "25 horas",
    skills: [S.PHP, S.BACKEND, S.API],
    url: "https://laracasts.com/",
  },
  {
    id: "course-34",
    title: "R Programming A-Z",
    provider: "Udemy",
    duration: "11 horas",
    skills: [S.R_LANG, S.DATA_SCIENCE],
    url: "https://www.udemy.com/",
  },
  {
    id: "course-35",
    title: "Ruby on Rails — The Complete Guide",
    provider: "Udemy",
    duration: "35 horas",
    skills: [S.RUBY, S.BACKEND, S.API, S.REST],
    url: "https://www.udemy.com/",
  },
  {
    id: "course-36",
    title: "Rust — The Complete Developer's Guide",
    provider: "Udemy",
    duration: "28 horas",
    skills: [S.RUST, S.BACKEND],
    url: "https://www.udemy.com/",
  },
  {
    id: "course-37",
    title: "Scala & Functional Programming",
    provider: "Coursera",
    duration: "45 horas",
    skills: [S.SCALA, S.BACKEND],
    url: "https://www.coursera.org/",
  },
  {
    id: "course-38",
    title: "iOS & Swift — The Complete App Development Bootcamp",
    provider: "Udemy",
    duration: "60 horas",
    skills: [S.SWIFT, S.MOBILE, S.UIUX],
    url: "https://www.udemy.com/",
  },
  {
    id: "course-39",
    title: "Product Management 101",
    provider: "Coursera",
    duration: "15 horas",
    skills: [S.PRODUCT_MANAGEMENT],
    url: "https://www.coursera.org/",
  },
  {
    id: "course-40",
    title: "Introduction to IoT",
    provider: "Cisco Networking Academy",
    duration: "20 horas",
    skills: [S.IOT, S.CLOUD, S.SECURITY],
    url: "https://www.netacad.com/",
  },
];
