export const SKILL = {
  FRONTEND: "frontend",
  BACKEND: "backend",
  MOBILE: "mobile",
  FULLSTACK: "fullstack",
  REACT: "react",
  ANGULAR: "angular",
  VUE: "vue",
  SVELTE: "svelte",
  NEXTJS: "nextjs",
  JAVASCRIPT: "javascript",
  TYPESCRIPT: "typescript",
  NODE: "node",
  JAVA: "java",
  PYTHON: "python",
  CSHARP: "csharp",
  KOTLIN: "kotlin",
  SWIFT: "swift",
  RUST: "rust",
  PHP: "php",
  RUBY: "ruby",
  GO: "go",
  DART: "dart",
  SCALA: "scala",
  SQL: "sql",
  NOSQL: "nosql",
  DATABASE: "database",
  API: "api",
  REST: "rest",
  GRAPHQL: "graphql",
  CSS: "css",
  UIUX: "uiux",
  GIT: "git",
  LINUX: "linux",
  DOCKER: "docker",
  KUBERNETES: "kubernetes",
  DEVOPS: "devops",
  CLOUD: "cloud",
  CICD: "cicd",
  TESTING: "testing",
  SECURITY: "security",
  AI: "ai",
  DATA_SCIENCE: "data_science",
  BLOCKCHAIN: "blockchain",
  GAME_DEV: "game_development",
  CPP: "cpp",
  R_LANG: "r",
  PRODUCT_MANAGEMENT: "product_management",
  IOT: "iot",
} as const;

export type Skill = (typeof SKILL)[keyof typeof SKILL];

export const SKILL_LABELS: Record<Skill, string> = {
  frontend: "Frontend",
  backend: "Backend",
  mobile: "Mobile",
  fullstack: "Full Stack",
  react: "React",
  angular: "Angular",
  vue: "Vue.js",
  svelte: "Svelte",
  nextjs: "Next.js",
  javascript: "JavaScript",
  typescript: "TypeScript",
  node: "Node.js",
  java: "Java",
  python: "Python",
  csharp: "C#",
  kotlin: "Kotlin",
  swift: "Swift",
  rust: "Rust",
  php: "PHP",
  ruby: "Ruby",
  go: "Go",
  dart: "Dart",
  scala: "Scala",
  sql: "SQL",
  nosql: "NoSQL",
  database: "Bases de datos",
  api: "APIs",
  rest: "REST",
  graphql: "GraphQL",
  css: "CSS",
  uiux: "UI/UX",
  git: "Git",
  linux: "Linux",
  docker: "Docker",
  kubernetes: "Kubernetes",
  devops: "DevOps",
  cloud: "Cloud",
  cicd: "CI/CD",
  testing: "Testing",
  security: "Seguridad",
  ai: "IA / ML",
  data_science: "Ciencia de datos",
  blockchain: "Blockchain",
  game_development: "Game Development",
  cpp: "C++",
  r: "R",
  product_management: "Product Management",
  iot: "IoT",
};
