import type { Skill } from "./skills";
import { SKILL as S } from "./skills";

export const TECHNOLOGY_TO_SKILLS: Record<string, Skill[]> = {
  JavaScript: [S.JAVASCRIPT],
  TypeScript: [S.TYPESCRIPT, S.JAVASCRIPT],
  Python: [S.PYTHON],
  Java: [S.JAVA],
  "C#": [S.CSHARP],
  "C++": [S.CPP],
  Go: [S.GO],
  Rust: [S.RUST],
  Ruby: [S.RUBY],
  PHP: [S.PHP],
  Kotlin: [S.KOTLIN],
  Swift: [S.SWIFT],
  Dart: [S.DART],
  Scala: [S.SCALA],
  R: [S.R_LANG, S.DATA_SCIENCE],
  SQL: [S.SQL, S.DATABASE],
  React: [S.FRONTEND, S.REACT, S.JAVASCRIPT],
  Angular: [S.FRONTEND, S.ANGULAR, S.TYPESCRIPT, S.JAVASCRIPT],
  "Vue.js": [S.FRONTEND, S.VUE, S.JAVASCRIPT],
  Svelte: [S.FRONTEND, S.SVELTE, S.JAVASCRIPT],
  "Next.js": [S.FRONTEND, S.REACT, S.NEXTJS, S.JAVASCRIPT],
  Nuxt: [S.FRONTEND, S.VUE, S.JAVASCRIPT],
  Django: [S.BACKEND, S.PYTHON, S.API, S.REST],
  Flask: [S.BACKEND, S.PYTHON, S.API, S.REST],
  FastAPI: [S.BACKEND, S.PYTHON, S.API, S.REST],
  "Spring Boot": [S.BACKEND, S.JAVA, S.API, S.REST],
  ".NET": [S.BACKEND, S.CSHARP, S.API, S.REST],
  Express: [S.BACKEND, S.NODE, S.JAVASCRIPT, S.API, S.REST],
  NestJS: [S.BACKEND, S.NODE, S.TYPESCRIPT, S.API, S.REST],
  Laravel: [S.BACKEND, S.PHP, S.API, S.REST],
  "Ruby on Rails": [S.BACKEND, S.RUBY, S.API, S.REST],
  Flutter: [S.MOBILE, S.DART, S.FRONTEND],
  "React Native": [S.MOBILE, S.REACT, S.JAVASCRIPT],
  Electron: [S.FRONTEND, S.JAVASCRIPT, S.NODE],
  PostgreSQL: [S.DATABASE, S.SQL],
  MySQL: [S.DATABASE, S.SQL],
  MongoDB: [S.DATABASE, S.NOSQL],
  Redis: [S.DATABASE, S.NOSQL],
  SQLite: [S.DATABASE, S.SQL],
  Firebase: [S.DATABASE, S.NOSQL, S.CLOUD],
  DynamoDB: [S.DATABASE, S.NOSQL, S.CLOUD],
  Elasticsearch: [S.DATABASE, S.NOSQL],
  Docker: [S.DOCKER, S.DEVOPS],
  Kubernetes: [S.KUBERNETES, S.DEVOPS, S.CLOUD],
  AWS: [S.CLOUD, S.DEVOPS],
  Azure: [S.CLOUD, S.DEVOPS],
  GCP: [S.CLOUD, S.DEVOPS],
  Terraform: [S.CLOUD, S.DEVOPS],
  Ansible: [S.DEVOPS, S.LINUX],
  "CI/CD": [S.CICD, S.DEVOPS],
  Linux: [S.LINUX],
  Git: [S.GIT],
  Figma: [S.UIUX],
  Jira: [S.CICD],
  Notion: [S.UIUX],
  GraphQL: [S.GRAPHQL, S.API],
  "REST API": [S.REST, S.API],
  Webpack: [S.FRONTEND, S.JAVASCRIPT],
  Vite: [S.FRONTEND, S.JAVASCRIPT],
  "Tailwind CSS": [S.CSS, S.FRONTEND],
  Sass: [S.CSS, S.FRONTEND],
};
