"""Skill definitions, technology mapping, mock jobs and courses.

This mirrors frontend/src/lib/matching/ — keep both in sync.
"""
from dataclasses import dataclass, field
from typing import Dict, List, Optional

# ── Skills ──────────────────────────────────────────────────────────────────

SKILLS: Dict[str, str] = {
    "FRONTEND": "frontend",
    "BACKEND": "backend",
    "MOBILE": "mobile",
    "FULLSTACK": "fullstack",
    "REACT": "react",
    "ANGULAR": "angular",
    "VUE": "vue",
    "SVELTE": "svelte",
    "NEXTJS": "nextjs",
    "JAVASCRIPT": "javascript",
    "TYPESCRIPT": "typescript",
    "NODE": "node",
    "JAVA": "java",
    "PYTHON": "python",
    "CSHARP": "csharp",
    "KOTLIN": "kotlin",
    "SWIFT": "swift",
    "RUST": "rust",
    "PHP": "php",
    "RUBY": "ruby",
    "GO": "go",
    "DART": "dart",
    "SCALA": "scala",
    "CPP": "cpp",
    "R_LANG": "r",
    "SQL": "sql",
    "NOSQL": "nosql",
    "DATABASE": "database",
    "API": "api",
    "REST": "rest",
    "GRAPHQL": "graphql",
    "CSS": "css",
    "UIUX": "uiux",
    "GIT": "git",
    "LINUX": "linux",
    "DOCKER": "docker",
    "KUBERNETES": "kubernetes",
    "DEVOPS": "devops",
    "CLOUD": "cloud",
    "CICD": "cicd",
    "TESTING": "testing",
    "SECURITY": "security",
    "AI": "ai",
    "DATA_SCIENCE": "data_science",
    "BLOCKCHAIN": "blockchain",
    "GAME_DEV": "game_development",
    "PRODUCT_MANAGEMENT": "product_management",
    "IOT": "iot",
}

S = SKILLS  # shorthand alias for inline use

SKILL_VALUES = frozenset(SKILLS.values())

SKILL_LABELS: Dict[str, str] = {
    "frontend": "Frontend",
    "backend": "Backend",
    "mobile": "Mobile",
    "fullstack": "Full Stack",
    "react": "React",
    "angular": "Angular",
    "vue": "Vue.js",
    "svelte": "Svelte",
    "nextjs": "Next.js",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "node": "Node.js",
    "java": "Java",
    "python": "Python",
    "csharp": "C#",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "rust": "Rust",
    "php": "PHP",
    "ruby": "Ruby",
    "go": "Go",
    "dart": "Dart",
    "scala": "Scala",
    "cpp": "C++",
    "r": "R",
    "sql": "SQL",
    "nosql": "NoSQL",
    "database": "Bases de datos",
    "api": "APIs",
    "rest": "REST",
    "graphql": "GraphQL",
    "css": "CSS",
    "uiux": "UI/UX",
    "git": "Git",
    "linux": "Linux",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "devops": "DevOps",
    "cloud": "Cloud",
    "cicd": "CI/CD",
    "testing": "Testing",
    "security": "Seguridad",
    "ai": "IA / ML",
    "data_science": "Ciencia de datos",
    "blockchain": "Blockchain",
    "game_development": "Game Development",
    "product_management": "Product Management",
    "iot": "IoT",
}

# ── Types ───────────────────────────────────────────────────────────────────

@dataclass
class UserSkillProfile:
    skills: List[str] = field(default_factory=list)
    custom_technologies: List[str] = field(default_factory=list)


@dataclass
class MatchResult:
    score: float = 0.0
    matched_required: List[str] = field(default_factory=list)
    matched_optional: List[str] = field(default_factory=list)
    missing_required: List[str] = field(default_factory=list)
    missing_optional: List[str] = field(default_factory=list)
    recommended_course_ids: List[str] = field(default_factory=list)


@dataclass
class Job:
    id: str
    title: str
    company: str
    location: str
    description: str
    area: str = ""
    required_skills: List[str] = field(default_factory=list)
    optional_skills: List[str] = field(default_factory=list)
    salary: Optional[str] = None
    seniority: str = "junior"


@dataclass
class Course:
    id: str
    title: str
    provider: str
    duration: str
    skills: List[str] = field(default_factory=list)
    url: Optional[str] = None

# ── Technology → Skills Mapping ─────────────────────────────────────────────

TECHNOLOGY_TO_SKILLS: Dict[str, List[str]] = {
    "JavaScript": [S["JAVASCRIPT"]],
    "TypeScript": [S["TYPESCRIPT"], S["JAVASCRIPT"]],
    "Python": [S["PYTHON"]],
    "Java": [S["JAVA"]],
    "C#": [S["CSHARP"]],
    "C++": [S["CPP"]],
    "Go": [S["GO"]],
    "Rust": [S["RUST"]],
    "Ruby": [S["RUBY"]],
    "PHP": [S["PHP"]],
    "Kotlin": [S["KOTLIN"]],
    "Swift": [S["SWIFT"]],
    "Dart": [S["DART"]],
    "Scala": [S["SCALA"]],
    "R": [S["R_LANG"], S["DATA_SCIENCE"]],
    "SQL": [S["SQL"], S["DATABASE"]],
    "React": [S["FRONTEND"], S["REACT"], S["JAVASCRIPT"]],
    "Angular": [S["FRONTEND"], S["ANGULAR"], S["TYPESCRIPT"], S["JAVASCRIPT"]],
    "Vue.js": [S["FRONTEND"], S["VUE"], S["JAVASCRIPT"]],
    "Svelte": [S["FRONTEND"], S["SVELTE"], S["JAVASCRIPT"]],
    "Next.js": [S["FRONTEND"], S["REACT"], S["NEXTJS"], S["JAVASCRIPT"]],
    "Nuxt": [S["FRONTEND"], S["VUE"], S["JAVASCRIPT"]],
    "Django": [S["BACKEND"], S["PYTHON"], S["API"], S["REST"]],
    "Flask": [S["BACKEND"], S["PYTHON"], S["API"], S["REST"]],
    "FastAPI": [S["BACKEND"], S["PYTHON"], S["API"], S["REST"]],
    "Spring Boot": [S["BACKEND"], S["JAVA"], S["API"], S["REST"]],
    ".NET": [S["BACKEND"], S["CSHARP"], S["API"], S["REST"]],
    "Express": [S["BACKEND"], S["NODE"], S["JAVASCRIPT"], S["API"], S["REST"]],
    "NestJS": [S["BACKEND"], S["NODE"], S["TYPESCRIPT"], S["API"], S["REST"]],
    "Laravel": [S["BACKEND"], S["PHP"], S["API"], S["REST"]],
    "Ruby on Rails": [S["BACKEND"], S["RUBY"], S["API"], S["REST"]],
    "Flutter": [S["MOBILE"], S["DART"], S["FRONTEND"]],
    "React Native": [S["MOBILE"], S["REACT"], S["JAVASCRIPT"]],
    "Electron": [S["FRONTEND"], S["JAVASCRIPT"], S["NODE"]],
    "PostgreSQL": [S["DATABASE"], S["SQL"]],
    "MySQL": [S["DATABASE"], S["SQL"]],
    "MongoDB": [S["DATABASE"], S["NOSQL"]],
    "Redis": [S["DATABASE"], S["NOSQL"]],
    "SQLite": [S["DATABASE"], S["SQL"]],
    "Firebase": [S["DATABASE"], S["NOSQL"], S["CLOUD"]],
    "DynamoDB": [S["DATABASE"], S["NOSQL"], S["CLOUD"]],
    "Elasticsearch": [S["DATABASE"], S["NOSQL"]],
    "Docker": [S["DOCKER"], S["DEVOPS"]],
    "Kubernetes": [S["KUBERNETES"], S["DEVOPS"], S["CLOUD"]],
    "AWS": [S["CLOUD"], S["DEVOPS"]],
    "Azure": [S["CLOUD"], S["DEVOPS"]],
    "GCP": [S["CLOUD"], S["DEVOPS"]],
    "Terraform": [S["CLOUD"], S["DEVOPS"]],
    "Ansible": [S["DEVOPS"], S["LINUX"]],
    "CI/CD": [S["CICD"], S["DEVOPS"]],
    "Linux": [S["LINUX"]],
    "Git": [S["GIT"]],
    "Figma": [S["UIUX"]],
    "Jira": [S["CICD"]],
    "Notion": [S["UIUX"]],
    "GraphQL": [S["GRAPHQL"], S["API"]],
    "REST API": [S["REST"], S["API"]],
    "Webpack": [S["FRONTEND"], S["JAVASCRIPT"]],
    "Vite": [S["FRONTEND"], S["JAVASCRIPT"]],
    "Tailwind CSS": [S["CSS"], S["FRONTEND"]],
    "Sass": [S["CSS"], S["FRONTEND"]],
}

# Also map skill values directly (for new registration form where users pick skills)
for _val in SKILL_VALUES:
    if _val not in TECHNOLOGY_TO_SKILLS:
        TECHNOLOGY_TO_SKILLS[_val] = [_val]

# ── Mock Jobs (40) ──────────────────────────────────────────────────────────

MOCK_JOBS: List[Job] = [
    Job(id="job-fe-01", area="frontend", title="Desarrollador Frontend React", company="Mercado Libre",
        location="Remoto — LATAM", seniority="semi-senior", salary="ARS 1.800.000 - 2.500.000",
        description="Construí la cara visible de la plataforma de e-commerce más grande de LATAM. Diseñarás interfaces que usan millones de personas todos los días, con un equipo que prioriza la calidad de código y el crecimiento profesional.",
        required_skills=[S["FRONTEND"], S["REACT"], S["JAVASCRIPT"], S["CSS"]],
        optional_skills=[S["TYPESCRIPT"], S["NEXTJS"], S["GIT"], S["TESTING"]]),
    Job(id="job-fe-02", area="frontend", title="Frontend Developer Angular", company="Accenture",
        location="Buenos Aires, AR", seniority="junior", salary="ARS 1.500.000 - 2.200.000",
        description="Transformá la experiencia digital de empresas Fortune 500 desde Buenos Aires. Trabajás con Angular en proyectos internacionales donde tu código impacta a miles de usuarios corporativos.",
        required_skills=[S["FRONTEND"], S["ANGULAR"], S["TYPESCRIPT"], S["CSS"]],
        optional_skills=[S["JAVASCRIPT"], S["REST"], S["GIT"], S["TESTING"]]),
    Job(id="job-fe-03", area="frontend", title="Vue.js Developer", company="Cencosud",
        location="Remoto — Chile / Argentina", seniority="semi-senior", salary="USD 2.000 - 3.000",
        description="Dale forma a la transformación digital del retail líder en LATAM. Tus dashboards con Vue.js 3 guiarán decisiones que impactan a millones de clientes en toda la región.",
        required_skills=[S["FRONTEND"], S["VUE"], S["JAVASCRIPT"], S["CSS"]],
        optional_skills=[S["TYPESCRIPT"], S["REST"], S["GIT"], S["UIUX"]]),
    Job(id="job-fe-04", area="frontend", title="Svelte Developer", company="Vercel",
        location="Remoto — Global", seniority="senior", salary="USD 80.000 - 120.000",
        description="Unite al equipo que define el futuro del desarrollo web. En Vercel construirás componentes Svelte que empujan los límites de la velocidad y la experiencia de desarrollo.",
        required_skills=[S["FRONTEND"], S["SVELTE"], S["JAVASCRIPT"], S["CSS"]],
        optional_skills=[S["TYPESCRIPT"], S["NODE"], S["GIT"], S["TESTING"]]),
    Job(id="job-fe-05", area="frontend", title="Next.js & React Developer", company="Globant",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.000.000 - 2.800.000",
        description="Liderá la migración a Next.js del sistema core de un banco digital. Un proyecto de alto impacto donde cada PR mejora la experiencia de millones de usuarios financieros.",
        required_skills=[S["FRONTEND"], S["REACT"], S["NEXTJS"], S["JAVASCRIPT"]],
        optional_skills=[S["TYPESCRIPT"], S["GRAPHQL"], S["CSS"], S["TESTING"]]),
    Job(id="job-fe-06", area="frontend", title="UI Developer", company="Ualá",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 1.600.000 - 2.300.000",
        description="Definí cómo se ve y se siente la experiencia financiera de millones de argentinos. Crearás el design system que unifica todos los productos de Ualá, desde la app hasta la web.",
        required_skills=[S["FRONTEND"], S["CSS"], S["UIUX"], S["JAVASCRIPT"]],
        optional_skills=[S["REACT"], S["TYPESCRIPT"], S["GIT"], S["TESTING"]]),
    Job(id="job-fe-07", area="frontend", title="Desarrollador Web Accesibilidad", company="Despegar",
        location="Buenos Aires, AR", seniority="senior", salary="ARS 1.700.000 - 2.400.000",
        description="Hacé que viajar sea posible para todos. Liderarás la iniciativa de accesibilidad de Despegar, asegurando que cada persona — sin importar sus capacidades — pueda planificar su próximo destino.",
        required_skills=[S["FRONTEND"], S["CSS"], S["JAVASCRIPT"], S["UIUX"]],
        optional_skills=[S["REACT"], S["TYPESCRIPT"], S["TESTING"], S["GIT"]]),
    Job(id="job-fe-08", area="frontend", title="Frontend Developer Junior", company="PedidosYa",
        location="Remoto — LATAM", seniority="junior", salary="ARS 800.000 - 1.200.000",
        description="Empezá tu carrera en tecnología con el respaldo de un equipo que cree en vos. Aprendé React, testing y CI/CD con mentoría personalizada de seniors que quieren verte crecer.",
        required_skills=[S["FRONTEND"], S["JAVASCRIPT"], S["CSS"], S["GIT"]],
        optional_skills=[S["REACT"], S["TYPESCRIPT"], S["REST"], S["CICD"]]),
    Job(id="job-be-01", area="backend", title="Backend Developer Node.js", company="Rappi",
        location="Remoto — LATAM", seniority="semi-senior", salary="USD 3.500 - 5.000",
        description="Construí los servicios que procesan millones de pedidos en tiempo real. Tu código en Node.js será el corazón de Rappi, conectando restaurantes, repartidores y clientes en toda LATAM.",
        required_skills=[S["BACKEND"], S["NODE"], S["JAVASCRIPT"], S["API"], S["REST"]],
        optional_skills=[S["TYPESCRIPT"], S["DATABASE"], S["DOCKER"], S["CICD"]]),
    Job(id="job-be-02", area="backend", title="Python Developer — Django", company="Eventbrite",
        location="Remoto — Mendoza, AR", seniority="semi-senior", salary="ARS 2.200.000 - 3.000.000",
        description="Dale forma al futuro de los pagos globales. Trabajarás en el equipo de payments de Eventbrite, integrando gateways de pago para que cualquier persona en el mundo pueda asistir a eventos que la inspiren.",
        required_skills=[S["BACKEND"], S["PYTHON"], S["API"], S["REST"], S["DATABASE"]],
        optional_skills=[S["DOCKER"], S["TESTING"], S["GIT"], S["GRAPHQL"]]),
    Job(id="job-be-03", area="backend", title="Backend Python — FastAPI", company="Tiendanube",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 1.900.000 - 2.600.000",
        description="Creá las APIs que sostienen a miles de emprendedores. En Tiendanube construirás la columna vertebral de la plataforma de e-commerce, con Python moderno y un stack que prioriza la simplicidad.",
        required_skills=[S["BACKEND"], S["PYTHON"], S["API"], S["REST"], S["DATABASE"]],
        optional_skills=[S["DOCKER"], S["DEVOPS"], S["TESTING"], S["GIT"]]),
    Job(id="job-be-04", area="backend", title="Java Backend Developer", company="Santander Tecnología",
        location="Buenos Aires, AR", seniority="senior", salary="ARS 2.500.000 - 3.500.000",
        description="Construí sistemas que mueven la economía real. En Santander desarrollarás servicios bancarios de misión crítica — cada transacción, cada préstamo, cada sueño pasa por tu código.",
        required_skills=[S["BACKEND"], S["JAVA"], S["API"], S["REST"], S["SQL"]],
        optional_skills=[S["DOCKER"], S["KUBERNETES"], S["TESTING"], S["SECURITY"]]),
    Job(id="job-be-05", area="backend", title=".NET Developer", company="Globant",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.100.000 - 3.000.000",
        description="Liderá la modernización tecnológica de una aseguradora centenaria. Migrarás sistemas legacy a .NET 8 con microservicios, transformando cómo la empresa sirve a sus clientes.",
        required_skills=[S["BACKEND"], S["CSHARP"], S["API"], S["REST"], S["SQL"]],
        optional_skills=[S["DOCKER"], S["CLOUD"], S["CICD"], S["TESTING"]]),
    Job(id="job-be-06", area="backend", title="Go Backend Engineer", company="Mercado Libre",
        location="Remoto — LATAM", seniority="senior", salary="USD 5.000 - 7.500",
        description="Escribí el código que procesa pagos para medio continente. Tus servicios en Go manejarán transacciones financieras a escala masiva con la precisión que solo un lenguaje como Go puede ofrecer.",
        required_skills=[S["BACKEND"], S["GO"], S["API"], S["REST"], S["DATABASE"]],
        optional_skills=[S["DOCKER"], S["KUBERNETES"], S["CLOUD"], S["CICD"]]),
    Job(id="job-be-07", area="backend", title="Backend Developer PHP — Laravel", company="Aerolíneas Argentinas",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 1.500.000 - 2.000.000",
        description="Mantené los sistemas que mantienen a Argentina conectada. Tus aplicaciones Laravel gestionan vuelos, tripulaciones y pasajeros — el backend silencioso que hace posible cada despegue.",
        required_skills=[S["BACKEND"], S["PHP"], S["API"], S["REST"], S["SQL"]],
        optional_skills=[S["DOCKER"], S["GIT"], S["TESTING"], S["LINUX"]]),
    Job(id="job-be-08", area="backend", title="Backend Trainee Node.js", company="Coderhouse",
        location="Remoto — Argentina", seniority="trainee", salary="ARS 500.000 - 700.000",
        description="Empezá tu camino en backend con el equipo que formó a cientos de developers. Aprendé Node.js, Express y bases de datos con mentoría de seniors que recuerdan exactamente cómo se siente empezar.",
        required_skills=[S["BACKEND"], S["JAVASCRIPT"], S["GIT"]],
        optional_skills=[S["NODE"], S["REST"], S["DATABASE"], S["TYPESCRIPT"]]),
    Job(id="job-fs-01", area="fullstack", title="Full Stack TypeScript Developer", company="Airtable",
        location="Remoto — Global", seniority="senior", salary="USD 90.000 - 130.000",
        description="Construí el producto que usan equipos de todo el mundo para colaborar visualmente. Full stack TypeScript de punta a punta — React en el front, Node.js en el back — en una de las startups más queridas del ecosistema SaaS.",
        required_skills=[S["FRONTEND"], S["BACKEND"], S["TYPESCRIPT"], S["REACT"], S["NODE"]],
        optional_skills=[S["GRAPHQL"], S["DATABASE"], S["DOCKER"], S["CICD"]]),
    Job(id="job-fs-02", area="fullstack", title="Full Stack Python + React", company="Mural",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.500.000 - 3.500.000",
        description="Creá la plataforma que redefine cómo los equipos visualizan ideas. Stack híbrido con React y TypeScript en el frontend y Python con Django en el backend — lo mejor de dos mundos.",
        required_skills=[S["FRONTEND"], S["BACKEND"], S["REACT"], S["PYTHON"], S["DATABASE"]],
        optional_skills=[S["TYPESCRIPT"], S["DOCKER"], S["REST"], S["TESTING"]]),
    Job(id="job-fs-03", area="fullstack", title="Full Stack Java + Angular", company="Telefónica",
        location="Remoto — LATAM", seniority="semi-senior", salary="ARS 2.000.000 - 2.800.000",
        description="Conectá a millones de personas con el stack que sostiene las telecomunicaciones de LATAM. Angular y TypeScript en el frontend, Spring Boot y Java en el backend — una arquitectura sólida donde cada capa importa.",
        required_skills=[S["FRONTEND"], S["BACKEND"], S["ANGULAR"], S["JAVA"], S["SQL"]],
        optional_skills=[S["TYPESCRIPT"], S["DOCKER"], S["REST"], S["TESTING"]]),
    Job(id="job-fs-04", area="fullstack", title="MERN Stack Developer", company="Startup — EdTech",
        location="Remoto — LATAM", seniority="semi-senior", salary="USD 2.500 - 4.000",
        description="Convertite en el primer ingeniero de una startup EdTech que va a cambiar cómo miles de estudiantes aprenden. Stack MERN desde cero — vos decidís la arquitectura, vos dejás tu huella.",
        required_skills=[S["FRONTEND"], S["BACKEND"], S["REACT"], S["NODE"], S["NOSQL"]],
        optional_skills=[S["TYPESCRIPT"], S["DOCKER"], S["CSS"], S["GIT"]]),
    Job(id="job-fs-05", area="fullstack", title="Full Stack Developer Junior", company="Wolox",
        location="Remoto — Argentina", seniority="junior", salary="ARS 900.000 - 1.300.000",
        description="Aprendé el stack completo con el equipo que formó a los mejores developers de Argentina. Rotación real entre frontend y backend — en 6 meses vas a entender cómo se construye un producto de punta a punta.",
        required_skills=[S["FRONTEND"], S["BACKEND"], S["JAVASCRIPT"], S["GIT"]],
        optional_skills=[S["REACT"], S["NODE"], S["DATABASE"], S["CSS"]]),
    Job(id="job-mo-01", area="mobile", title="React Native Developer", company="Rappi",
        location="Remoto — LATAM", seniority="semi-senior", salary="USD 3.000 - 4.500",
        description="Dale vida a las features que millones de personas usan para pedir comida, hacer mercado y enviar paquetes. Tu código React Native corre en cada celular de LATAM.",
        required_skills=[S["MOBILE"], S["REACT"], S["JAVASCRIPT"], S["FRONTEND"]],
        optional_skills=[S["TYPESCRIPT"], S["CSS"], S["REST"], S["GIT"]]),
    Job(id="job-mo-02", area="mobile", title="Flutter Developer", company="Frávega",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 1.800.000 - 2.500.000",
        description="Creá la experiencia de compra del futuro. Liderarás la migración de Frávega a Flutter — una app unificada para iOS y Android que redefine cómo los argentinos compran tecnología.",
        required_skills=[S["MOBILE"], S["DART"], S["FRONTEND"], S["API"]],
        optional_skills=[S["REST"], S["GIT"], S["TESTING"], S["UIUX"]]),
    Job(id="job-mo-03", area="mobile", title="iOS Developer — Swift", company="PedidosYa",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 2.000.000 - 2.800.000",
        description="Construí la app que lleva comida a millones de hogares. Desarrollo nativo con Swift y SwiftUI en estrecha colaboración con diseño y producto — cada animación, cada gesto, cada pixel importa.",
        required_skills=[S["MOBILE"], S["SWIFT"], S["UIUX"]],
        optional_skills=[S["API"], S["REST"], S["GIT"], S["TESTING"]]),
    Job(id="job-mo-04", area="mobile", title="Android Developer — Kotlin", company="Banco Galicia",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 2.200.000 - 3.000.000",
        description="Creá la app que permite a millones de personas manejar su plata desde el celular. Kotlin, Jetpack Compose y Clean Architecture en el equipo mobile del banco más innovador de Argentina.",
        required_skills=[S["MOBILE"], S["KOTLIN"], S["SECURITY"]],
        optional_skills=[S["API"], S["REST"], S["GIT"], S["TESTING"]]),
    Job(id="job-do-01", area="devops", title="DevOps Engineer", company="Mercado Libre",
        location="Remoto — LATAM", seniority="senior", salary="USD 5.000 - 7.000",
        description="Diseñá y operá la infraestructura que sostiene al e-commerce más grande de LATAM. CI/CD, Kubernetes y monitoreo para cientos de microservicios — cada deploy tuyo impacta a millones.",
        required_skills=[S["DEVOPS"], S["CLOUD"], S["CICD"], S["DOCKER"], S["KUBERNETES"]],
        optional_skills=[S["LINUX"], S["GIT"], S["SECURITY"], S["TESTING"]]),
    Job(id="job-do-02", area="cloud", title="Cloud Architect — AWS", company="Globant",
        location="Remoto — Argentina", seniority="senior", salary="ARS 3.000.000 - 4.500.000",
        description="Arquitectura cloud al servicio de clientes Fortune 500. Diseñarás migraciones a AWS con Terraform, optimizando costos y seguridad — la nube bien hecha transforma negocios.",
        required_skills=[S["CLOUD"], S["DEVOPS"], S["DOCKER"], S["KUBERNETES"], S["SECURITY"]],
        optional_skills=[S["LINUX"], S["CICD"], S["DATABASE"], S["GIT"]]),
    Job(id="job-do-03", area="devops", title="SRE — Site Reliability Engineer", company="Ualá",
        location="Remoto — Argentina", seniority="senior", salary="ARS 2.800.000 - 4.000.000",
        description="Protegé los ahorros de millones de argentinos. Como SRE de Ualá, garantizarás que la plataforma financiera nunca falle — SLOs, observabilidad y automatización de incidentes.",
        required_skills=[S["DEVOPS"], S["CLOUD"], S["KUBERNETES"], S["DOCKER"], S["LINUX"]],
        optional_skills=[S["CICD"], S["GIT"], S["DATABASE"], S["TESTING"]]),
    Job(id="job-do-04", area="devops", title="Platform Engineer Junior", company="Despegar",
        location="Buenos Aires, AR", seniority="junior", salary="ARS 1.200.000 - 1.800.000",
        description="Empezá en platform engineering con el equipo que te va a enseñar todo. Kubernetes, CI/CD y cloud de la mano de seniors que quieren compartir lo que saben.",
        required_skills=[S["DEVOPS"], S["DOCKER"], S["LINUX"], S["GIT"]],
        optional_skills=[S["CLOUD"], S["KUBERNETES"], S["CICD"], S["PYTHON"]]),
    Job(id="job-da-01", area="data_science", title="Data Scientist", company="Mercado Libre",
        location="Remoto — LATAM", seniority="senior", salary="USD 4.500 - 6.500",
        description="Aplicá ciencia de datos a escala continental. Modelarás pricing dinámico y sistemas de recomendación con terabytes de datos reales — tu trabajo define qué ven y qué pagan millones de personas.",
        required_skills=[S["DATA_SCIENCE"], S["PYTHON"], S["SQL"], S["AI"]],
        optional_skills=[S["R_LANG"], S["CLOUD"], S["GIT"], S["API"]]),
    Job(id="job-da-02", area="ai_ml", title="Machine Learning Engineer", company="Rappi",
        location="Remoto — LATAM", seniority="senior", salary="USD 5.000 - 7.000",
        description="Ponele ingeniería a la inteligencia artificial. Llevarás modelos de ML a producción con prácticas MLOps de clase mundial — feature stores, monitoreo y CI/CD para modelos que impactan millones de entregas.",
        required_skills=[S["AI"], S["PYTHON"], S["DEVOPS"], S["CLOUD"], S["DOCKER"]],
        optional_skills=[S["SQL"], S["DATA_SCIENCE"], S["GIT"], S["KUBERNETES"]]),
    Job(id="job-da-03", area="data_science", title="Data Engineer", company="Tiendanube",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.500.000 - 3.500.000",
        description="Construí las tuberías de datos que alimentan cada decisión de Tiendanube. Pipelines ETL con Spark y Airflow sobre arquitectura lakehouse — ingeniería de datos al servicio de miles de emprendedores.",
        required_skills=[S["DATA_SCIENCE"], S["SQL"], S["PYTHON"], S["CLOUD"], S["DEVOPS"]],
        optional_skills=[S["DOCKER"], S["DATABASE"], S["GIT"], S["NOSQL"]]),
    Job(id="job-da-04", area="ai_ml", title="AI Engineer — LLMs", company="Startup — AgTech",
        location="Remoto — Argentina", seniority="senior", salary="ARS 3.000.000 - 4.500.000",
        description="Poné la inteligencia artificial al servicio del campo. Integrarás LLMs con RAG para crear asistentes que ayudan a productores agropecuarios a tomar mejores decisiones — tecnología de punta con impacto real.",
        required_skills=[S["AI"], S["PYTHON"], S["API"], S["REST"], S["CLOUD"]],
        optional_skills=[S["DATA_SCIENCE"], S["DOCKER"], S["GIT"], S["SQL"]]),
    Job(id="job-qa-01", area="qa_testing", title="QA Automation Engineer", company="Santander Tecnología",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 1.800.000 - 2.500.000",
        description="Garantizá que cada release de la plataforma bancaria sea sólida como una roca. Automatizarás tests E2E con Cypress y Selenium — tu trabajo evita bugs antes de que lleguen a producción.",
        required_skills=[S["TESTING"], S["JAVASCRIPT"], S["API"], S["GIT"]],
        optional_skills=[S["TYPESCRIPT"], S["CICD"], S["DOCKER"], S["SQL"]]),
    Job(id="job-qa-02", area="qa_testing", title="SDET — Software Dev in Test", company="Ualá",
        location="Remoto — Argentina", seniority="senior", salary="ARS 2.200.000 - 3.200.000",
        description="Creá las herramientas de testing que usan todos los equipos de ingeniería de Ualá. Contract testing, chaos engineering y frameworks internos para microservicios.",
        required_skills=[S["TESTING"], S["PYTHON"], S["DEVOPS"], S["DOCKER"], S["CICD"]],
        optional_skills=[S["JAVA"], S["GIT"], S["SQL"], S["KUBERNETES"]]),
    Job(id="job-se-01", area="cybersecurity", title="Application Security Engineer", company="Mercado Pago",
        location="Remoto — LATAM", seniority="senior", salary="USD 5.000 - 7.000",
        description="Protegé la plataforma de pagos más grande de LATAM. Seguridad ofensiva y defensiva — SAST, DAST y threat modeling para blindar millones de transacciones financieras.",
        required_skills=[S["SECURITY"], S["BACKEND"], S["CLOUD"], S["API"], S["DOCKER"]],
        optional_skills=[S["PYTHON"], S["JAVA"], S["KUBERNETES"], S["CICD"]]),
    Job(id="job-se-02", area="cybersecurity", title="DevSecOps Engineer", company="Despegar",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 2.500.000 - 3.500.000",
        description="Hacé que la seguridad sea invisible y omnipresente. Automatizarás escaneos de vulnerabilidades y gestión de secretos en el pipeline de CI/CD de Despegar.",
        required_skills=[S["SECURITY"], S["DEVOPS"], S["CICD"], S["DOCKER"], S["KUBERNETES"]],
        optional_skills=[S["CLOUD"], S["LINUX"], S["GIT"], S["TESTING"]]),
    Job(id="job-bc-01", area="blockchain", title="Smart Contract Developer", company="Ripio",
        location="Remoto — Argentina", seniority="semi-senior", salary="USD 3.500 - 5.500",
        description="Escribí el código que custodia activos digitales de miles de usuarios. Smart contracts en Solidity para el exchange crypto líder de LATAM — cada línea de código es un compromiso de seguridad.",
        required_skills=[S["BLOCKCHAIN"], S["JAVASCRIPT"], S["SECURITY"], S["API"], S["GIT"]],
        optional_skills=[S["PYTHON"], S["TESTING"], S["DOCKER"], S["CLOUD"]]),
    Job(id="job-bc-02", area="blockchain", title="Web3 Frontend Developer", company="Lemon Cash",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.500.000 - 3.500.000",
        description="Construí la experiencia web de la wallet crypto más querida de Argentina. React, Web3 y wallets on-chain — conectando a miles de usuarios con el mundo cripto de forma simple y segura.",
        required_skills=[S["FRONTEND"], S["REACT"], S["BLOCKCHAIN"], S["JAVASCRIPT"], S["CSS"]],
        optional_skills=[S["TYPESCRIPT"], S["NEXTJS"], S["SECURITY"], S["GIT"]]),
    Job(id="job-gd-01", area="game_development", title="Unity Developer", company="Etermax",
        location="Buenos Aires, AR", seniority="semi-senior", salary="ARS 1.800.000 - 2.500.000",
        description="Creá los juegos que millones de personas juegan en el bondi, en la fila del banco, en su casa. Unity y C# de punta a punta — desde el prototipo hasta el feature en la App Store.",
        required_skills=[S["GAME_DEV"], S["CSHARP"], S["MOBILE"], S["UIUX"]],
        optional_skills=[S["CPP"], S["GIT"], S["CLOUD"], S["TESTING"]]),
    Job(id="job-gd-02", area="game_development", title="Gameplay Programmer Junior", company="Nimble Giant",
        location="Remoto — Argentina", seniority="trainee", salary="ARS 600.000 - 900.000",
        description="Dá tus primeros pasos en la industria del gaming con el estudio más grande de LATAM. Aprendé C++ y Unreal Engine de la mano de desarrolladores que publicaron títulos AAA.",
        required_skills=[S["GAME_DEV"], S["CPP"], S["GIT"]],
        optional_skills=[S["CSHARP"], S["LINUX"], S["TESTING"], S["UIUX"]]),
    Job(id="job-pm-01", area="product_management", title="Product Manager Jr — Tech", company="Mercado Libre",
        location="Buenos Aires, AR", seniority="junior", salary="ARS 2.000.000 - 2.800.000",
        description="Definí el futuro de los productos que usan millones de personas todos los días. Como PM en Mercado Libre, conectarás tecnología, negocio y experiencia de usuario para crear soluciones que transforman el comercio electrónico en LATAM.",
        required_skills=[S["PRODUCT_MANAGEMENT"], S["UIUX"], S["FRONTEND"]],
        optional_skills=[S["API"], S["GIT"], S["TESTING"], S["DATA_SCIENCE"]]),
    Job(id="job-pm-02", area="product_management", title="Technical Product Manager", company="Ualá",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.500.000 - 3.500.000",
        description="Liderá la visión de producto de la fintech que está revolucionando la inclusión financiera en Argentina. Combinarás pensamiento estratégico con conocimiento técnico para priorizar features que impactan la vida financiera de millones de personas.",
        required_skills=[S["PRODUCT_MANAGEMENT"], S["API"], S["SECURITY"], S["UIUX"]],
        optional_skills=[S["FRONTEND"], S["BACKEND"], S["GIT"], S["DATA_SCIENCE"]]),
    Job(id="job-io-01", area="iot", title="IoT Developer", company="Globant",
        location="Remoto — Argentina", seniority="semi-senior", salary="ARS 2.300.000 - 3.200.000",
        description="Conectá el mundo físico con el digital. Desarrollarás soluciones IoT para industrias como agricultura inteligente, ciudades conectadas y manufactura 4.0 — sensores, edge computing y cloud trabajando en armonía.",
        required_skills=[S["IOT"], S["CLOUD"], S["PYTHON"], S["API"], S["SECURITY"]],
        optional_skills=[S["DOCKER"], S["DEVOPS"], S["GIT"], S["LINUX"]]),
    Job(id="job-io-02", area="iot", title="Embedded Systems Engineer — IoT", company="Intel",
        location="Remoto — LATAM", seniority="semi-senior", salary="USD 4.000 - 6.000",
        description="Diseñá el firmware que corre en millones de dispositivos conectados. Trabajarás en la intersección de hardware y software — embedded systems, protocolos IoT y edge computing para la próxima generación de dispositivos inteligentes.",
        required_skills=[S["IOT"], S["CPP"], S["LINUX"], S["SECURITY"]],
        optional_skills=[S["CLOUD"], S["PYTHON"], S["GIT"], S["DOCKER"]]),
]

# ── Mock Courses (30) ───────────────────────────────────────────────────────

MOCK_COURSES: List[Course] = [
    Course(id="course-01", title="React — The Complete Guide", provider="Udemy",
           duration="48 horas", skills=[S["REACT"], S["FRONTEND"], S["JAVASCRIPT"]],
           url="https://www.udemy.com/course/react-the-complete-guide/"),
    Course(id="course-02", title="TypeScript Deep Dive", provider="Frontend Masters",
           duration="8 horas", skills=[S["TYPESCRIPT"], S["JAVASCRIPT"]],
           url="https://frontendmasters.com/courses/typescript-v4/"),
    Course(id="course-03", title="Next.js Foundations", provider="Vercel",
           duration="6 horas", skills=[S["NEXTJS"], S["REACT"], S["FRONTEND"], S["JAVASCRIPT"]],
           url="https://nextjs.org/learn"),
    Course(id="course-04", title="Vue 3 Masterclass", provider="Vue School",
           duration="30 horas", skills=[S["VUE"], S["FRONTEND"], S["JAVASCRIPT"]],
           url="https://vueschool.io/courses"),
    Course(id="course-05", title="Angular — The Complete Guide", provider="Udemy",
           duration="36 horas", skills=[S["ANGULAR"], S["FRONTEND"], S["TYPESCRIPT"]],
           url="https://www.udemy.com/course/the-complete-guide-to-angular-2/"),
    Course(id="course-06", title="Svelte for Beginners", provider="freeCodeCamp",
           duration="4 horas", skills=[S["SVELTE"], S["FRONTEND"], S["JAVASCRIPT"]],
           url="https://www.freecodecamp.org/"),
    Course(id="course-07", title="CSS for JS Developers", provider="Josh Comeau",
           duration="20 horas", skills=[S["CSS"], S["FRONTEND"], S["UIUX"]],
           url="https://css-for-js.dev/"),
    Course(id="course-08", title="Node.js — From Zero to Expert", provider="Udemy",
           duration="40 horas", skills=[S["NODE"], S["BACKEND"], S["JAVASCRIPT"], S["API"]],
           url="https://www.udemy.com/course/nodejs-the-complete-guide/"),
    Course(id="course-09", title="Python for Everybody", provider="Coursera",
           duration="64 horas", skills=[S["PYTHON"], S["DATABASE"], S["SQL"]],
           url="https://www.coursera.org/specializations/python"),
    Course(id="course-10", title="Django for Professionals", provider="Platzi",
           duration="25 horas", skills=[S["BACKEND"], S["PYTHON"], S["API"], S["REST"], S["DATABASE"]],
           url="https://platzi.com/cursos/django/"),
    Course(id="course-11", title="FastAPI — Modern Python Web", provider="freeCodeCamp",
           duration="8 horas", skills=[S["BACKEND"], S["PYTHON"], S["API"], S["REST"]],
           url="https://www.freecodecamp.org/"),
    Course(id="course-12", title="Spring Boot 3 & Spring Framework 6", provider="Udemy",
           duration="32 horas", skills=[S["BACKEND"], S["JAVA"], S["API"], S["REST"], S["SQL"]],
           url="https://www.udemy.com/course/spring-boot-and-spring-framework-tutorial/"),
    Course(id="course-13", title="Go Programming — Mastering the Language", provider="Coursera",
           duration="30 horas", skills=[S["GO"], S["BACKEND"], S["API"]],
           url="https://www.coursera.org/specializations/google-golang"),
    Course(id="course-14", title="SQL for Data Analysis", provider="DataCamp",
           duration="10 horas", skills=[S["SQL"], S["DATABASE"]],
           url="https://www.datacamp.com/courses/introduction-to-sql"),
    Course(id="course-15", title="MongoDB University", provider="MongoDB",
           duration="15 horas", skills=[S["NOSQL"], S["DATABASE"]],
           url="https://learn.mongodb.com/"),
    Course(id="course-16", title="Docker & Kubernetes Complete Guide", provider="KodeKloud",
           duration="32 horas", skills=[S["DOCKER"], S["KUBERNETES"], S["DEVOPS"], S["CLOUD"]],
           url="https://kodekloud.com/"),
    Course(id="course-17", title="AWS Cloud Practitioner Essentials", provider="AWS Skill Builder",
           duration="6 horas", skills=[S["CLOUD"], S["DEVOPS"]],
           url="https://aws.amazon.com/training/"),
    Course(id="course-18", title="CI/CD with GitHub Actions", provider="freeCodeCamp",
           duration="3 horas", skills=[S["CICD"], S["DEVOPS"], S["GIT"]],
           url="https://www.freecodecamp.org/"),
    Course(id="course-19", title="Linux Command Line Basics", provider="Udacity",
           duration="3 horas", skills=[S["LINUX"], S["DEVOPS"]],
           url="https://www.udacity.com/course/linux-command-line-basics--ud595"),
    Course(id="course-20", title="Testing JavaScript Applications", provider="Frontend Masters",
           duration="10 horas", skills=[S["TESTING"], S["JAVASCRIPT"], S["NODE"]],
           url="https://frontendmasters.com/courses/testing-javascript/"),
    Course(id="course-21", title="React Native — The Practical Guide", provider="Udemy",
           duration="38 horas", skills=[S["MOBILE"], S["REACT"], S["JAVASCRIPT"], S["FRONTEND"]],
           url="https://www.udemy.com/course/react-native-the-practical-guide/"),
    Course(id="course-22", title="Flutter & Dart — Complete Guide", provider="Udemy",
           duration="42 horas", skills=[S["MOBILE"], S["DART"], S["FRONTEND"]],
           url="https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/"),
    Course(id="course-23", title="DevOps Foundations", provider="Platzi",
           duration="20 horas", skills=[S["DEVOPS"], S["DOCKER"], S["CICD"], S["LINUX"], S["CLOUD"]],
           url="https://platzi.com/cursos/devops/"),
    Course(id="course-24", title="Machine Learning — Stanford", provider="Coursera",
           duration="60 horas", skills=[S["AI"], S["DATA_SCIENCE"], S["PYTHON"]],
           url="https://www.coursera.org/learn/machine-learning"),
    Course(id="course-25", title="Blockchain A-Z — Build a Blockchain", provider="Udemy",
           duration="20 horas", skills=[S["BLOCKCHAIN"], S["PYTHON"], S["SECURITY"]],
           url="https://www.udemy.com/course/build-your-blockchain-az/"),
    Course(id="course-26", title="Complete C# Unity Game Developer", provider="Udemy",
           duration="50 horas", skills=[S["GAME_DEV"], S["CSHARP"], S["MOBILE"]],
           url="https://www.udemy.com/course/unitycourse2/"),
    Course(id="course-27", title="API Design & REST Fundamentals", provider="freeCodeCamp",
           duration="4 horas", skills=[S["API"], S["REST"], S["BACKEND"]],
           url="https://www.freecodecamp.org/"),
    Course(id="course-28", title="GraphQL with Apollo", provider="Apollo Graph Academy",
           duration="12 horas", skills=[S["GRAPHQL"], S["API"], S["FRONTEND"], S["BACKEND"]],
           url="https://www.apollographql.com/tutorials/"),
    Course(id="course-29", title="Application Security Fundamentals", provider="OWASP",
           duration="8 horas", skills=[S["SECURITY"], S["BACKEND"], S["API"]],
           url="https://owasp.org/"),
    Course(id="course-30", title="Kotlin for Android Developers", provider="Google",
           duration="20 horas", skills=[S["MOBILE"], S["KOTLIN"]],
           url="https://developer.android.com/courses"),
    Course(id="course-31", title="C++ Fundamentals", provider="freeCodeCamp",
           duration="12 horas", skills=[S["CPP"]],
           url="https://www.freecodecamp.org/"),
    Course(id="course-32", title="Full Stack Web Development", provider="Coursera",
           duration="40 horas", skills=[S["FULLSTACK"], S["FRONTEND"], S["BACKEND"], S["NODE"]],
           url="https://www.coursera.org/"),
    Course(id="course-33", title="PHP & Laravel — From Scratch", provider="Laracasts",
           duration="25 horas", skills=[S["PHP"], S["BACKEND"], S["API"]],
           url="https://laracasts.com/"),
    Course(id="course-34", title="R Programming A-Z", provider="Udemy",
           duration="11 horas", skills=[S["R_LANG"], S["DATA_SCIENCE"]],
           url="https://www.udemy.com/"),
    Course(id="course-35", title="Ruby on Rails — The Complete Guide", provider="Udemy",
           duration="35 horas", skills=[S["RUBY"], S["BACKEND"], S["API"], S["REST"]],
           url="https://www.udemy.com/"),
    Course(id="course-36", title="Rust — The Complete Developer's Guide", provider="Udemy",
           duration="28 horas", skills=[S["RUST"], S["BACKEND"]],
           url="https://www.udemy.com/"),
    Course(id="course-37", title="Scala & Functional Programming", provider="Coursera",
           duration="45 horas", skills=[S["SCALA"], S["BACKEND"]],
           url="https://www.coursera.org/"),
    Course(id="course-38", title="iOS & Swift — The Complete App Development Bootcamp", provider="Udemy",
           duration="60 horas", skills=[S["SWIFT"], S["MOBILE"], S["UIUX"]],
           url="https://www.udemy.com/"),
    Course(id="course-39", title="Product Management 101", provider="Coursera",
           duration="15 horas", skills=[S["PRODUCT_MANAGEMENT"]],
           url="https://www.coursera.org/"),
    Course(id="course-40", title="Introduction to IoT", provider="Cisco Networking Academy",
           duration="20 horas", skills=[S["IOT"], S["CLOUD"], S["SECURITY"]],
           url="https://www.netacad.com/"),
]

# Index courses by id for fast lookup
COURSE_BY_ID: Dict[str, Course] = {c.id: c for c in MOCK_COURSES}
