export const SKILL_LABELS: Record<string, string> = {
  frontend: "Frontend",
  backend: "Backend",
  mobile: "Mobile",
  fullstack: "Full Stack",
  react: "React",
  angular: "Angular",
  vue: "Vue.js",
  svelte: "Svelte",
  nextjs: "Next.js",
  javascript: "JavaScript",
  typescript: "TypeScript",
  node: "Node.js",
  java: "Java",
  python: "Python",
  csharp: "C#",
  kotlin: "Kotlin",
  swift: "Swift",
  rust: "Rust",
  php: "PHP",
  ruby: "Ruby",
  go: "Go",
  dart: "Dart",
  scala: "Scala",
  cpp: "C++",
  r: "R",
  sql: "SQL",
  nosql: "NoSQL",
  database: "Bases de datos",
  api: "APIs",
  rest: "REST",
  graphql: "GraphQL",
  css: "CSS",
  uiux: "UI/UX",
  git: "Git",
  linux: "Linux",
  docker: "Docker",
  kubernetes: "Kubernetes",
  devops: "DevOps",
  cloud: "Cloud",
  cicd: "CI/CD",
  testing: "Testing",
  security: "Seguridad",
  ai: "IA / ML",
  data_science: "Ciencia de datos",
  blockchain: "Blockchain",
  game_development: "Game Development",
  product_management: "Product Management",
  iot: "IoT",
};